---
aws_region: us-east-2

student_count: 1
student_prefix: cisco-student

# Enter the VPC ID below if using existing VPC. Comment if creating new VPC, it will be populated here upon creation.
# vpc_id: vpc-0b60cc1d07160596b

# Enter the IG_ID if using existing VPC. Comment if auto-creating new VPC by commenting out the VPC above.
# internet_gateway_id: igw-036df93d2c7cc253b 
subnet_range_primary: 10.1.0.0/16
subnet_range_secondary: 198.18.0.0/16

# S3 Bucket is global DNS unique name, use any arbitrary desired non-overlapping name. Will be created if doesn't exist.
s3_bucket: 'deft2-tetration-hol-cft-template' 

# This is your own private on-prem ISE instance - needs VPN with AWS VGW. If not using ISE simply give it any value, however do not comment. 
ise_server_ip: '172.16.171.49' 

asav_ami: ami-0cc6d931eeb481121
eks_worker_ami: ami-0c12dc9171d7252ad
ldap_ami: ami-063ca8b269537841f
mssql_ami: ami-090a4930496cbe28a
iis_ami: ami-02066420ce75afcb0
mysql_ami: ami-0caaa7c0eadaec7b5
apache_ami: ami-01d583af8e8932759
ansible_ami: ami-02e353df2bfb03bc1
tet_data_ami: ami-014df3ebd0af05bbe
tet_edge_ami: ami-028c27c2b07a3aee7
employee_ubuntu_ami: ami-08f5365f20685309f
sysadmin_ubuntu_ami: ami-08f5365f20685309f
attack_server_ami: ami-0011d2ead8e1e276f
guacamole_ami: ami-0a4a0a2c7dd763d53
