---
aws_region: us-west-2
student_prefix: cisco-student
student_count: 1
# Enter the VPC ID below if using existing VPC. Comment if creating new VPC, it will be populated here upon creation.
# vpc_id: vpc-0f7e98ab606236278

# Enter the IG_ID if using existing VPC. Comment if auto-creating new VPC by commenting out the VPC above.
# internet_gateway_id: igw-03ba648c46f5d4614
subnet_range_primary: '10.1.0.0/16'
subnet_range_secondary: '198.18.0.0/16'

# This is your own private on-prem ISE instance - needs VPN with AWS VGW. If not using ISE simply give it any value, however do not comment. 
ise_server_ip: '172.16.171.49' 

asav_ami: ami-03ad81377648fcb21
eks_worker_ami: ami-0d3dd0a90d88054ac
ldap_ami: ami-023f6bde07f76f00d
mssql_ami: ami-055820d5169ca780d
iis_ami: ami-072e21835272f1132
mysql_ami: ami-01c356f1ec0f4286e
apache_ami: ami-0a4ee97e3189d4148
ansible_ami: ami-0a2fbe66b5295e758
tet_data_ami: ami-0ad43fe5c904c9d11
tet_edge_ami: ami-0c4aa3cbc3f97d345
employee_ubuntu_ami: ami-0b8c7764f803d9bc6
sysadmin_ubuntu_ami: ami-0b8c7764f803d9bc6
attack_server_ami: ami-06fb8b1d5809dec8a
guacamole_ami: ami-06f977c2b543da32a
