---
# Prefer using Env Vars to set AWS Access & Secret Keys named as such:
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY 
# This template for Deft Ohio region 10.0 vpc
aws_access_key: 
aws_secret_key: 
aws_region: us-east-2

student_count: 1
student_prefix: cisco-student

vpc_cidr: 10.1.0.0/16 # << the CIDR block to assign to the VPC if creating a new VPC
#vpc_id: vpc-017dd7e8fc4a4b9de # << Enter the VPC ID if using existing VPC. Comment if creating new VPC.
#internet_gateway_id: igw-0dbfdfc228666cee0 # << Enter the IG_ID if using existing VPC. Comment if creating new VPC.
subnet_range_primary: 10.1.0.0/16
subnet_range_secondary: 198.18.0.0/16

s3_bucket: 'deft-tetration-hol-cft-template' # << S3 Bucket is global DNS unique name - create S3 bucket first with any arbitrary desired non-overlapping name

ise_server_ip: '172.16.171.49' # << This is your own private on-prem ISE instance - needs VPN with AWS VGW

asav_ami: ami-0f3cca6491d987102 # << Needs subscription from AWS Marketplace (search for ASAv BYOL)
eks_worker_ami: ami-0c4c60006aa81c29b # << Global AWS Marketplace - will change with region - https://cloud-images.ubuntu.com/docs/aws/eks/
ldap_ami: ami-023d4d7de3b45e49f
mssql_ami: ami-036f338ef7bd53f28
iis_ami: ami-0ec2ebbac543d4b92
mysql_ami: ami-03090b35eec7a3ea3
apache_ami: ami-0c13fecb95acf9047
ansible_ami: ami-03f343687182b4f56
tet_data_ami: ami-0616a0dd164002c82
tet_edge_ami: ami-0d68a248955f00e67
employee_ubuntu_ami: ami-05ef8c95c82fad367
sysadmin_ubuntu_ami: ami-05ef8c95c82fad367
attack_server_ami: ami-072b3b226d4a24ccd
guacamole_ami: ami-099d4d0da973f9b98

