apiVersion: v1
kind: Service
metadata:
  name: lb
  labels:
    name: front-end
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
  type: LoadBalancer